#!/usr/bin/env python3
import os
import sys
import time
import urllib.parse

# =================================================
# 1. 配置区域
# =================================================
REPO_ROOT = os.getcwd()
MERGED_DIR = os.path.join(REPO_ROOT, "merged-rules")
README_FILE = os.path.join(REPO_ROOT, "README.md")

# 动态获取仓库信息 (例如: yourname/your-repo)
REPO_NAME = os.getenv("GITHUB_REPOSITORY", "Outcome/Rule-Set")
BRANCH_NAME = os.getenv("GITHUB_REF_NAME", "main")
OWNER_NAME = REPO_NAME.split("/")[0]

# 基础链接构建
BASE_RAW = f"https://raw.githubusercontent.com/{REPO_NAME}/{BRANCH_NAME}"
BASE_MIRROR = f"https://raw.gitmirror.com/{REPO_NAME}/{BRANCH_NAME}"
BASE_GHPROXY = f"https://ghproxy.net/{BASE_RAW}"

# 样式配置
SHIELDS_STYLE = "flat-square"

# =================================================
# 2. 辅助函数
# =================================================

def format_size(size_bytes):
    """将字节转换为人类可读格式 (KB, MB)"""
    if size_bytes == 0: return "0 B"
    units = ("B", "KB", "MB", "GB")
    i = 0
    p = size_bytes
    while p >= 1024 and i < len(units) - 1:
        p /= 1024
        i += 1
    return f"{p:.2f} {units[i]}"

def get_current_time_str():
    """生成 URL 编码的时间字符串"""
    now = time.strftime("%Y-%m-%d %H:%M")
    return urllib.parse.quote(now)

def scan_rules():
    """扫描合并目录"""
    rule_files = []
    if not os.path.exists(MERGED_DIR):
        return []
    for root, _, files in os.walk(MERGED_DIR):
        for file in files:
            # 只要是文件就列出来，不限制后缀
            if not file.startswith("."):
                full_path = os.path.join(root, file)
                rule_files.append(full_path)
    return sorted(rule_files)

# =================================================
# 3. 模板 (样式参考版 - 内容已通用化)
# =================================================

HEADER_TEMPLATE = f"""<div align="center">

<!-- 标题 -->
<h1>{REPO_NAME.split('/')[-1]}</h1>

<!-- Badges 徽章区域 -->
[![Build Status](https://img.shields.io/github/actions/workflow/status/{REPO_NAME}/sync-rules.yml?style={SHIELDS_STYLE}&logo=github&label=Build)](https://github.com/{REPO_NAME}/actions)
[![Repo Size](https://img.shields.io/github/repo-size/{REPO_NAME}?style={SHIELDS_STYLE}&label=Size&color=orange)](https://github.com/{REPO_NAME})
[![Updated](https://img.shields.io/badge/Updated-{get_current_time_str()}-blue?style={SHIELDS_STYLE}&logo=time)](https://github.com/{REPO_NAME}/commits/{BRANCH_NAME})

<p>
🚀 <strong>Auto Updates</strong> · 🌏 <strong>Global CDN</strong> · 🎯 <strong>Categorized</strong>
</p>
</div>

<!-- 三列特性表格 -->
<table>
<thead>
<tr>
<th align="center">🤖 <strong>Automated</strong></th>
<th align="center">⚡ <strong>Fast</strong></th>
<th align="center">📦 <strong>Organized</strong></th>
</tr>
</thead>
<tbody>
<tr>
<td align="center">Daily upstream sync<br>Auto-merge & clean</td>
<td align="center">Multi-CDN support<br>GhProxy / GitMirror</td>
<td align="center">Structured folders<br>Generic compatibility</td>
</tr>
</tbody>
</table>

---

## ⚙️ 使用说明 (Usage)

<div class="markdown-alert markdown-alert-tip">
<p class="markdown-alert-title">Tip</p>
<p>推荐使用 <strong>GhProxy</strong> 通道以下载规则，可获得更快的国内访问速度。</p>
</div>

<details>
<summary><strong>📝 点击查看引用链接示例</strong></summary>

使用以下链接格式引用规则：

- **GhProxy (推荐)**: `https://ghproxy.net/{BASE_RAW}/merged-rules/Category/Name.txt`
- **GitMirror**: `https://raw.gitmirror.com/{REPO_NAME}/{BRANCH_NAME}/merged-rules/Category/Name.txt`
- **GitHub Raw**: `{BASE_RAW}/merged-rules/Category/Name.txt`

</details>

## 📥 规则列表 (Downloads)

<div class="markdown-alert markdown-alert-note">
<p class="markdown-alert-title">Note</p>
<p>点击 <code>🚀 Fast Download</code> 按钮可直接获取加速链接。</p>
</div>

| 规则名称 (Name) | 类型 (Ext) | 大小 (Size) | 下载通道 (Download) |
| :--- | :--- | :--- | :--- |
"""

FOOTER_TEMPLATE = """
<div align="center">
<br>
<p><strong>Total Files:</strong> <code>{count}</code></p>
<p><a href="#">🔼 Back to Top</a></p>
<sub>Generated by GitHub Actions</sub>
</div>
"""

# =================================================
# 4. 执行生成
# =================================================

def main():
    print("::group::📝 Generating README...")
    
    files = scan_rules()
    print(f"::notice::Found {len(files)} files to list.")

    try:
        with open(README_FILE, 'w', encoding='utf-8') as f:
            f.write(HEADER_TEMPLATE)
            
            if not files:
                f.write("| ❌ Emtpy | - | - | - |\n")
            else:
                for filepath in files:
                    filename = os.path.basename(filepath)
                    filesize = os.path.getsize(filepath)
                    human_size = format_size(filesize)
                    extension = os.path.splitext(filename)[1].replace(".", "").upper() or "FILE"
                    
                    # 路径处理
                    display_path = os.path.relpath(filepath, MERGED_DIR) # e.g. reject/domain/geo.txt
                    subdir = os.path.dirname(display_path)               # e.g. reject/domain
                    
                    # 显示路径 (样式优化: 📂 reject/domain /)
                    dir_tag = f"📂 {subdir} /" if subdir else "📂 Root /"

                    # URL 生成 (强制 /)
                    url_path = display_path.replace(os.sep, '/')
                    link_ghproxy = f"{BASE_GHPROXY}/merged-rules/{url_path}"
                    link_mirror = f"{BASE_MIRROR}/merged-rules/{url_path}"
                    link_raw = f"{BASE_RAW}/merged-rules/{url_path}"
                    
                    # 写入行
                    row = (
                        f"| <sub>{dir_tag}</sub><br>**{filename}** | "
                        f"`{extension}` | "
                        f"`{human_size}` | "
                        f'<a href="{link_ghproxy}"><img src="https://img.shields.io/badge/🚀_Fast_Download-GhProxy-009688?style={SHIELDS_STYLE}&logo=rocket" alt="Fast Download"></a><br>'
                        f"[CDN Mirror]({link_mirror}) • [Raw Source]({link_raw}) |\n"
                    )
                    f.write(row)

            f.write(FOOTER_TEMPLATE.format(count=len(files)))
            
        print("::endgroup::")
        print("✅ README.md updated.")
        
    except Exception as e:
        print(f"::error::Error generating README: {e}")
        sys.exit(1)

if __name__ == "__main__":
    main()
