import os
import sys
import shutil
import subprocess
import json
import datetime
import zipfile

TARGET_CONFIG = {
    "merged-rules": ".txt",
    "merged-rules-mrs": ".mrs"
}
KEEP_DAYS = 3

def run_gh(cmd_list):
    """调用 GitHub CLI，简化报错处理"""
    try:
        result = subprocess.run(["gh"] + cmd_list, capture_output=True, text=True, check=True)
        return result.stdout.strip()
    except subprocess.CalledProcessError as e:
        print(f"⚠️ GH API Note: {e.stderr.strip()}")
        return None

def zip_target_files(tag_date):
    """
    压缩文件并返回: (压缩包名, 文件清单字典)
    """
    zip_name = f"merged-rules-{tag_date}.zip"
    print(f"📦 Packaging files into {zip_name}...")
    
    file_manifest = {}
    total_files = 0
    
    with zipfile.ZipFile(zip_name, 'w', zipfile.ZIP_DEFLATED) as zipf:
        for folder, ext in TARGET_CONFIG.items():
            if not os.path.exists(folder):
                print(f"⚠️ Warning: Directory '{folder}' not found. Skipping.")
                continue

            file_manifest[folder] = []
            print(f"   -> Scanning '{folder}' for *{ext} files...")
            
            for root, _, files in os.walk(folder):
                for file in files:
                    if file.endswith(ext):
                        file_path = os.path.join(root, file)
                        arcname = os.path.join(folder, file) 
                        zipf.write(file_path, arcname)
                        
                        file_manifest[folder].append(file)
                        total_files += 1
    
    if total_files == 0:
        print("❌ Error: No matching files found to pack!")
        sys.exit(1)
        
    return zip_name, file_manifest

def generate_release_notes(tag_date, tag_time, manifest):
    """生成漂亮的 Markdown 发布说明"""
    
    txt_count = len(manifest.get("merged-rules", []))
    mrs_count = len(manifest.get("merged-rules-mrs", []))
    total_count = txt_count + mrs_count
    
    details_md = ""
    for folder, files in manifest.items():
        if files:
            icon = "📝" if "txt" in TARGET_CONFIG.get(folder, "") else "🧩"
            details_md += f"#### {icon} {folder} ({len(files)})\n"
            files.sort()
            for f in files:
                details_md += f"- `{f}`\n"
            details_md += "\n"

    commit_sha = os.getenv("GITHUB_SHA", "unknown")[:7]

    notes = f"""
## 🚀 规则集合自动构建 (Auto Build)

> **更新时间**: `{tag_date} {tag_time}` (北京时间)  
> **触发提交**: `{commit_sha}`

### 📊 概览统计 (Summary)

| 规则类型 | 来源目录 | 文件数量 | 格式 |
| :--- | :--- | :---: | :---: |
| 📝 文本规则 | `merged-rules` | **{txt_count}** | `.txt` |
| 🧩 MRS 规则 | `merged-rules-mrs` | **{mrs_count}** | `.mrs` |
| **总计** | - | **{total_count}** | - |

<details>
<summary>🔍 <b>点击查看详细文件列表 (File List)</b></summary>

{details_md}

</details>

---
*Generated by GitHub Actions • [查看构建日志]({os.getenv('GITHUB_SERVER_URL')}/{os.getenv('GITHUB_REPOSITORY')}/actions)*
    """
    return notes

def main():
    print("::group::🚀 Processing Release")

    utc_now = datetime.datetime.now(datetime.timezone.utc)
    beijing_now = utc_now + datetime.timedelta(hours=8)
    tag_date = beijing_now.strftime("%Y-%m-%d")
    tag_time = beijing_now.strftime("%H:%M:%S")
    release_tag = f"rules-{tag_date}"

    print(f"📅 Target Release Tag: {release_tag}")

    zip_file, manifest = zip_target_files(tag_date)

    if run_gh(["release", "view", release_tag]):
        print(f"🔄 Release {release_tag} exists. Deleting for update...")
        run_gh(["release", "delete", release_tag, "--yes"])
        run_gh(["api", "-X", "DELETE", f"repos/{{owner}}/{{repo}}/git/refs/tags/{release_tag}"])

    print("📝 Generating rich release notes...")
    notes = generate_release_notes(tag_date, tag_time, manifest)

    # 4. 创建新 Release
    print(f"🚀 Uploading Release {release_tag}...")
    run_gh([
        "release", "create", release_tag, zip_file,
        "--title", f"Merged Rules - {tag_date}",
        "--notes", notes,
        "--latest"
    ])

    print(f"🧹 Cleaning up releases older than {KEEP_DAYS} days...")
    releases_json = run_gh(["release", "list", "--limit", "50", "--json", "tagName,createdAt"])
    
    if releases_json:
        releases = json.loads(releases_json)
        cutoff_time = utc_now - datetime.timedelta(days=KEEP_DAYS)
        
        for rel in releases:
            created_at = datetime.datetime.fromisoformat(rel['createdAt'].replace("Z", "+00:00"))
            tag = rel['tagName']
            
            if created_at < cutoff_time and tag != release_tag:
                print(f"🗑️ Deleting old release: {tag}")
                run_gh(["release", "delete", tag, "--yes"])
                run_gh(["api", "-X", "DELETE", f"repos/{{owner}}/{{repo}}/git/refs/tags/{tag}"])

    print("::endgroup::")
    print("✅ Feature Delivery Completed.")

if __name__ == "__main__":
    main()
